[package]
name = "first"
version = "0.1.0"
authors = ["Piotr Bielak <piotrbielak2@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
futures = "0.1"
env_logger = "0.6"
log = "0.4"
rand = "0.6"
time = "0.1"
